apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin
spec:
  replicas: 3
  template:
    metadata:
      labels:
        deployment: httpbin
    spec:
      containers:
      - name: httpbin
        image: kennethreitz/httpbin
        ports:
        - containerPort: 80
        env:
        - name: ALT_GREETING
          valueFrom:
            configMapKeyRef:
              name: httpbin-config
              key: greeting