kind: Service
apiVersion: v1
metadata:
  name: httpbin-service
spec:
  selector:
    deployment: httpbin
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: httpbin-metrics
spec:
  selector:
    deployment: httpbin
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8090